### ISSUE TITLE
`terraform destroy` fails

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke#3]
`terraform destroy` fails.
The error:
```
│ Error: Error deleting Feature: googleapi: Error 400: Feature has associated resources that should be cleaned up before deletion. Check the Feature state details for more information. This check can be overridden by setting force=true.
```

Logs just before the aforementioned logs:
```
google_container_cluster.my_cluster_canada: Destruction complete after 5m53s
google_container_cluster.my_cluster_usa: Still destroying... [id=projects/my-project-id/locations/us-west1/clusters/my-cluster-usa-1, 6m30s elapsed]
google_container_cluster.my_cluster_usa: Still destroying... [id=projects/my-project-id/locations/us-west1/clusters/my-cluster-usa-1, 6m40s elapsed]
google_container_cluster.my_cluster_usa: Still destroying... [id=projects/my-project-id/locations/us-west1/clusters/my-cluster-usa-1, 6m50s elapsed]
google_container_cluster.my_cluster_usa: Destruction complete after 6m54s
```

The US and Canada clusters were successfully deleted, but the deletion of the config cluster has not started.

#### Environment details

- Google Cloud Shell
- Terraform version: `v1.4.1`
- gcloud version: `Google Cloud SDK 422.0.0`
- kubectl version: N/A

#### Steps to reproduce

1. Go through the [quickstart](https://github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke#quickstart) to deploy the Terraform on a new GCP project.
2. Run `terraform destroy`.

**Comment by NimJay** [comment]
[Google Cloud doc about MCI](https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress#disabling): MCI and MCS K8s resources must be deleted prior to disabling the MCI feature.

**Comment by NimJay** [comment]
We cannot use [Terraform's kubernetes_manifest resource](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) because:
> This resource requires API access during planning time. This means the cluster has to be accessible at plan time and thus cannot be created in the same apply operation.

**Comment by NimJay** [comment]
This error seems to occur randomly. Here are some builds that successfully `terraform destroy`ed:
* https://github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke/runs/12644137076
* https://github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke/runs/12675942366

**Comment by bourgeoisor** [comment]
"This error seems to occur randomly" is this a race condition? Perhaps resources (or some resources) need to be destroyed in a particular order? (it seems very counter-IAC to say that, but it's a possibility)

**Comment by NimJay** [comment]
### Race condition?

> "is this a race condition?"

* That's a good question.
* I'll compare [this successful build](https://pantheon.corp.google.com/cloud-build/builds/ac9c3451-4a2e-49a1-aa32-eb99250ab969;step=4?project=cloud-foundation-cicd) with this [unsuccessful build](https://pantheon.corp.google.com/cloud-build/builds/37c1ca25-d2a5-495b-b3d5-410e69ad887c;step=4?project=cloud-foundation-cicd), and see if I find something interesting.
* One thing I'm noticing about the successful `terraform destroy` builds is that the deletion of the MCI feature happens very early. Example successful build [here](https://pantheon.corp.google.com/cloud-build/builds/ac9c3451-4a2e-49a1-aa32-eb99250ab969;step=4?project=cloud-foundation-cicd) and [here](https://pantheon.corp.google.com/cloud-build/builds/37c1ca25-d2a5-495b-b3d5-410e69ad887c;step=4?project=cloud-foundation-cicd). (Look for `multi_cluster_ingress_feature: Destruction complete`.)
* So as you suggested, maybe it's a matter of playing around with `depends_on` to ensure the MCI feature gets deleted early.

### My initial suspicions

* This whole time my suspicion was this statement [from docs.google.com](https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress#disabling):
> If you do not delete MultiClusterIngress and MultiClusterService resources before disabling Multi Cluster Ingress, you might encounter an error ...
> ...
> "Feature has associated resources that should be cleaned up before deletion."

* The error message is identical to what we're seeing.
* But the fact that we even have successful builds suggest that my suspicion is wrong, because the Terraform currently doesn't delete the `MultiClusterIngress` and `MultiClusterService` at all — because we use `local-exec` to deploy Kubernetes resources (and `local-exec`s don't get "reversed").

**Comment by NimJay** [comment]
From a Googler who ran into a similar issue ([b/267760268](http://b/267760268)):
> "When MCI/MCS k8s objects disappear on pantheon (or deleted by Terraform), it takes some time for the underlying resources provisioned by MCI/MCS (such as load balancing resources, NEGs, etc) to be completely deleted. IIUC, the associated features in MCI error message are referring to both MCI/MCS k8s objects and those underlying resources. Essentially, I think there's a race condition between when MCI/MCS k8s objects are completely deleted and when the MCI feature is turned off. That matches our observations that terraform destroy of the MCI feature is flaky. Sometimes it works, sometimes it doesn't."
