### ISSUE TITLE
`terraform apply` errs when MCI feature is already enabled

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke#32]
### Background
* MCI = multi-cluster ingress
* Inside [`/infra/multi_cluster_service.tf`](https://github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke/blob/f5083b8ceef259b8c6149a8eb80002c57847c2e3/infra/multi_cluster_service.tf#L36), we enable GKE Fleets' MCI feature using the [`google_gke_hub_feature`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature) Terraform resource.
* But this MCI feature is a singleton.
* In a non-Terraform world, this enablement is typically done via [`gcloud container fleet ingress enable`](https://cloud.google.com/sdk/gcloud/reference/container/fleet/ingress/enable).

### Problem
* If you `terraform apply` into a project where the MCI feature is already enabled, you will see this error:
```
Error: Error creating Feature: Resource already exists - apply blocked by lifecycle params: &beta.Feature{Name:(*string)(0xc00145aa10), Labels:map[string]string{}, ResourceState:(*beta.FeatureResourceState)(0xc00139b308), Spec:(*beta.FeatureSpec)(0xc001478010), State:(*beta.FeatureState)(0xc001478060), CreateTime:(*string)(0xc0014780f0), UpdateTime:(*string)(0xc001478100), DeleteTime:(*string)(nil), Project:(*string)(0xc00145aa50), Location:(*string)(0xc00145a9c0)}.
...
Error: running tf apply: terraform apply failed: running terraform failed: exit status 1
```
* When I produced this error on Solutions-in-Console (Jump Start Solutions), the deployment actually worked (but I saw the errors from the logs above in the SiC build logs, and ["Failed" on console UI](https://screenshot.googleplex.com/4GK2SZNjUGAq3z2.png)).

### Additional info
* From [cloud.google.com docs on "Fleet host project"](https://cloud.google.com/anthos/fleet-management/docs/fleet-concepts#fleet-host-project):
> A given Google Cloud project can only have a single fleet (or no fleets) associated with it.

**Comment by donmccasland** [comment]
This looks like an issue with the terraform provider, not with this solution
